name: Go CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Accuknox runtime monitoring
      uses: accuknox/report-action@v0.3.0    

    
    - name: Build
      run: go build -v ./...
    
