name: Go CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Run AccuKnox CI/CD Scan
      uses: accuknox/report-action@v0.3.1
      with:
        kubearmor_version: '1.3.4'

    - name: Build
      run: go build -v ./...
