name: Go CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Listen report 
      uses: listendev/action@v0.10.0
      with:
        jwt: ${{ secrets.LSTN_API_KEY }}
        ci: true

    - name: Build
      run: go build -v ./...
