name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3


    - name: Install KubeArmor
      run: |
        curl -L -o kubearmor_1.3.8_linux-amd64.deb https://github.com/kubearmor/KubeArmor/releases/download/v1.3.8/kubearmor_1.3.8_linux-amd64.deb
        sudo dpkg -i kubearmor_1.3.8_linux-amd64.deb
        sudo apt-get install -f

    - name: Verify KubeArmor Installation
      run: karmor version

    # - name: Start KubeArmor gRPC Service
    #   run: nohup kubearmor &
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Log KubeArmor gRPC Service Output
      run: |
        nohup sh -c 'while true; do
          karmor logs --logFilter=all --gRPC=:32767 --json >> kubearmor_logs.txt
          sleep 1
        done' &

    - name: Go mod tidy
      run: go mod tidy

    - name: Run vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...

    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Build
      run: go build -v ./...

    - name: Upload KubeArmor Logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: kubearmor-logs
        path: kubearmor_logs.txt

