name: Go CI/CD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Cimon by Cycode
      uses: CycodeLabs/cimon-action
    
    - name: Create and Run TCP Calls Script
      run: |
        cat << 'EOF' > tcp_calls.sh
        #!/bin/bash

        make_tcp_call() {
            ip=$1
            port=${2:-80}
            timeout=${3:-5}

            echo "Attempting to connect to $ip:$port"
            if nc -z -w $timeout $ip $port 2>/dev/null; then
                echo "Successfully connected to $ip:$port"
                echo -e "GET / HTTP/1.1\r\nHost: $ip\r\n\r\n" | nc -w $timeout $ip $port > /dev/null
            else
                echo "Failed to connect to $ip:$port"
            fi
        }

        main() {
            ips_to_call=(
                "8.8.8.8"        # Google DNS
                "1.1.1.1"        # Cloudflare DNS
                "172.217.16.142" # google.com
                "157.240.3.35"   # facebook.com
                "151.101.65.69"  # reddit.com
                "104.244.42.65"  # twitter.com
                "13.33.141.38"   # amazon.com
                "172.217.0.187"
            )

            echo "Starting TCP calls..."
            for ip in "${ips_to_call[@]}"; do
                make_tcp_call "$ip"
                sleep 1
            done
            echo "TCP calls completed."
        }

        main
        EOF
        
        chmod +x tcp_calls.sh
        ./tcp_calls.sh
    
    - name: Build
      run: go build -v ./...
